version: "3"
services:
  mongo:
    container-name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  
  api:
    container-name: api-container
    build: .
    restart: always
    image: clean-node-api
    command: npm start
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
    port:
      - "5050:5050"
    links:
      - mongo